--
-- PostgreSQL database dump
--

-- Dumped from database version 14.8 (Homebrew)
-- Dumped by pg_dump version 14.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: jialingye
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO jialingye;

--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: jialingye
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: jialingye
--

INSERT INTO auth_user VALUES (1, 'pbkdf2_sha256$600000$fElAxmGCgoRs1LoY55CwFb$piWOQIwoH9FQWohRlfgzO4OLje7y7AL1W7AFKDwpetQ=', '2023-07-10 11:51:31.396985-05', true, 'jialingye', '', '', '', true, true, '2023-07-10 11:51:20.277508-05');
INSERT INTO auth_user VALUES (2, 'pbkdf2_sha256$600000$kBsFe4ZIG8bH1d5QNonwG9$hd1AEqL7FUxJY0A9llVULhADaYpsCTUVVzrRp+Tjk+M=', NULL, false, 'student', '', '', '', false, true, '2023-07-14 21:53:26.249489-05');


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jialingye
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: jialingye
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

