# Generated by Django 4.2.2 on 2023-07-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_lesson_options_score_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInput',
        ),
    ]
