# Generated by Django 4.2.2 on 2023-07-17 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_course_tag_alter_coursecollection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecollection',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
